name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Thingies
      run: tar -cf - /usr/bin | xz -9 -c - > test.tar.xz
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: toolchain
        path: test.tar.xz
