name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: ./prepare-debian-ubuntu.sh
    - name: Remove dash pt.1
      run: echo "dash dash/sh boolean false"|sudo debconf-set-selections
    - name: Remove dash pt.2
      run: sudo dpkg-reconfigure --frontend=noninteractive dash
    - name: Compile
      run: sudo ./toolchain-sudo.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: toolchain
        path: /usr/local/pspdev
